cloud:
  aws:
    credentials:
      access-key: <insert value here>
      secret-key: <insert value here>
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: konkatvijaybkt


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090